name: residigital
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  lottie: ^1.2.2
  http: ^0.13.4
  screenshot: ^1.2.3
  modern_form_esys_flutter_share: ^1.1.2
  qr_flutter: ^4.0.0
  

dev_dependencies: 
  flutter_test: 
    sdk: flutter
   
    


flutter: 
  uses-material-design: true
  assets:
    - lib/app/images/
